[package]
name = "aurea"
version = "0.1.0"
edition = "2024"

[dependencies]

libc = "0.2"
log = "0.4.29"

[features]
default = []
wgpu = ["dep:wgpu", "dep:raw-window-handle"]

[dependencies.wgpu]
version = "28.0.0"
optional = true

[dependencies.raw-window-handle]
version = "0.6"
optional = true


[build-dependencies]
cc = "1.2"
pkg-config = "0.3"
